### ISSUE TITLE
soulfire client cannot connect

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#377] opened 2024-04-29 20:27 UTC

**Comment by TestingPlant** [comment] 2024-04-30 01:04
This seems to occur because the write is getting truncated. Currently writing code to fix that

**Comment by TestingPlant** [comment] 2024-05-04 20:40
It seems like this doesn't occur anymore, likely because smaller packets are being sent now instead of one large packet with every chunk. Will close this now that it's not a priority and is technically a duplicate of #303, but it should still be fixed at some point.

**Closed by TestingPlant** 2024-05-04 20:40 UTC
Labels: prio 🚨
