### ISSUE TITLE
fix arrow velocity/yaw/pitch (again?)

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#674] opened 2024-12-09 07:38 UTC
doesn't seem completely correct 🤔

<img width="380" alt="image" src="https://github.com/user-attachments/assets/30f7c718-16b0-4759-a315-d99c3f1971cc">

<img width="414" alt="image" src="https://github.com/user-attachments/assets/78fb50d2-3655-46d7-89e2-03bc9cbdb0c5">

<img width="2018" alt="image" src="https://github.com/user-attachments/assets/1b5f9595-d480-4766-ac7c-fea9808fe701">

**Comment by Tebarem** [comment] 2024-12-09 12:55
Do not use RotateAndMove. Just MoveRelative and Vel Update. The client should be able to handle the rotation on their side. The issue is we need to get the right calculation for Yaw and Pitch to attach an arrow into a player/block. Even then we might be able to just have the client guess the pitch and yaw

**Comment by andrewgazelka** [comment] 2024-12-09 20:03
> Do not use RotateAndMove. Just MoveRelative and Vel Update. The client should be able to handle the rotation on their side. The issue is we need to get the right calculation for Yaw and Pitch to attach an arrow into a player/block. Even then we might be able to just have the client guess the pitch and yaw

interesting cause seems like paper 1.20.1 was sending RotateAndMove + Vel update but maybe it doesn't need to?

**Comment by Kumpelinus** [comment] 2024-12-13 02:27
Fixed by #696

**Closed** 2024-12-13 18:14 UTC
